// <auto-generated />
namespace MGsTok.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class IlIlceAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IlIlceAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202103121151354_IlIlceAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
